version: '2'
services:
  alexey:
    build: .
    volumes:
      - "/opt/data:/var/run"
    links:
      - redis
    environment:
      REDIS_HOST: "redis"

  nginx:
    build: ./nginx
    ports:
      - "5296:5296"
    links:
      - alexey
    volumes_from:
      - alexey

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
